# Generated by Django 5.2.3 on 2025-07-06 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='cuantizacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
