# Generated by Django 5.2.3 on 2025-07-06 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_api', '0002_audiofile_cuantizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='tasa_muestreo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
