# Generated by Django 5.2.3 on 2025-07-06 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_api', '0003_audiofile_tasa_muestreo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='cuantizacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
